#!/usr/bin/perl -w
#
# Matrix Webhook for Hermod Gateway Bot.
#
# Receives events from matrix homeserver and forwards to telegram, mattermost,
# signal and/or irc
#
# 2026, Ruben de Groot

use strict;
use CGI::Fast qw/:standard/;
use JSON;
use TOML;
use URI::Escape;
use Capture::Tiny 'capture';
use Hermod;

my $msg;

open my $fh, '<', "/etc/hermod.toml" or die "error opening configuration $!";
my ($cfg, $e) = from_toml do { local $/; <$fh> };
unless ($cfg) {
    die "Error parsing toml: $e";
}
my $mtx = $cfg->{matrix} if defined $cfg->{matrix};

unless (defined $mtx->{token} and defined $mtx->{room} and defined  $mtx->{server} and defined $mtx->{bot}) {
    print "Please define matrix->token, room, server and bot\n";
    print "Press <Ctrl>-C to continue\n";
    sleep; exit;
}
open my $dbg, ">>", $mtx->{debug} if defined $mtx->{debug};
my $sig = $cfg->{signal} if defined $cfg->{signal};
my $tel = $cfg->{telegram} if defined $cfg->{telegram};
my $irc = $cfg->{irc} if defined $cfg->{irc};
my $mm = $cfg->{mattermost} if defined $cfg->{mattermost};
my $dis = $cfg->{discord} if defined $cfg->{discord};

while (my $cgi = CGI::Fast->new) {

    my $body = (defined $cgi->param('PUTDATA')) ? $cgi->param('PUTDATA') : '';
    unless ($body) { nok("missing body"); next; }

    my ($dj, $apidata);
    eval {
        $dj = decode_json( $body );
    };
    if ($@) {
        print $dbg "JSON decode error: $@\n";
        nok($@);
        next;
    }
    unless ((ref($dj) eq "HASH") and $dj->{'events'}) { nok("Not HASH or no events"); next; }
    for my $event (@{$dj->{events}}) {
        print $dbg %$event . "\n" if $dbg;
        next if $event->{sender} eq $mtx->{bot} or not $event->{sender} or not $event->{content}->{body};
        next unless $event->{room_id} eq $mtx->{room};
        $apidata->{sender} = "$event->{sender} in the matrix:";
        $apidata->{text} = $event->{content}->{body};
        my $inreply = $event->{content}->{'m.relates_to'}->{'m.in_reply_to'}->{event_id};
        $apidata->{quote} = getquote($mtx, $inreply) if $inreply;
        if ($event->{content}->{url} and $event->{content}->{url} =~ /^mxc:/) {
            # rework url to something browsers understand
            (my $srv = $event->{content}->{url}) =~ s#mxc://([a-z\.]+)/.*$#$1#;
            (my $id = $event->{content}->{url}) =~ s#.*/(\w*)#$1#;
            my ($ext) = $event->{content}->{body} =~ /(\.[^.]+)$/;
            qx( wget -O $mtx->{attachments}/$id$ext https://$srv/_matrix/media/r0/download/$srv/$id >/dev/null 2>&1 );
            push @{$apidata->{files}}, "$mtx->{attachments}/$id$ext";
        }
        print $dbg %$apidata . "\n" if $dbg;
        Hermod::relay2sigapi($apidata, $sig, $dbg);
        Hermod::relay2telapi($apidata, $tel, $dbg);
        Hermod::relay2mmapi($apidata, $mm, $dbg);
    }
    ok();
}

sub getquote {
    my ($mtx, $event) = @_;
    my $url = "$mtx->{server}/_matrix/client/v3/events/$event";
    my $ua = LWP::UserAgent->new(agent => "perl-matrix-client/1.0", timeout => 10);
    my $res = $ua->get($url, 'Authorization' => "Bearer $mtx->{token}");
    return unless $res->is_success;

    my $dj = decode_json($res->decoded_content);
    my $quote = ($dj->{sender} ne $mtx->{bot}) ? "Reply to $dj->{sender}\n" : '';
    return $quote . $dj->{content}->{body};
}

sub ok {
    print CGI->header(-type => 'application/json');
    print '{"ok":true,"status":200}'."\n\n";
}

sub nok {
    my $result = shift;
    print CGI->header(-type => 'application/json');
    print '{"ok":false,"status":502,"error":"'.$result.'"}'."\n\n";
}
